package com.local.deploy.projects.env

import java.io.File

object EnvManager {

    /**
     * Parses a .env file into key-value pairs, ignoring comments and whitespace.
     */
    fun parse(file: File): Map<String, String> {
        if (!file.exists() || !file.isFile) return emptyMap()
        val result = mutableMapOf<String, String>()

        file.readLines().forEach { rawLine ->
            val line = rawLine.trim()
            if (line.isNotEmpty() && !line.startsWith("#") && line.contains("=")) {
                val parts = line.split("=", limit = 2)
                val key = parts[0].trim()
                var value = parts.getOrNull(1)?.trim() ?: ""
                // Strip surrounding single/double quotes if present
                if ((value.startsWith("\"") && value.endsWith("\"")) ||
                    (value.startsWith("'") && value.endsWith("'"))
                ) {
                    if (value.length >= 2) {
                        value = value.substring(1, value.length - 1)
                    }
                }
                result[key] = value
            }
        }
        return result
    }

    fun read(file: File): Map<String, String> = parse(file)

    /**
     * Serializes environment variables into .env format and saves to target file.
     */
    fun write(file: File, envMap: Map<String, String>) {
        file.parentFile?.mkdirs()
        val sb = StringBuilder()
        sb.append("# Generated by Local Deploy Manager\n")
        envMap.forEach { (key, value) ->
            val escapedValue = if (value.contains(" ") || value.contains("#") || value.contains("\"")) {
                "\"${value.replace("\"", "\\\"")}\""
            } else {
                value
            }
            sb.append("$key=$escapedValue\n")
        }
        file.writeText(sb.toString())
    }

    /**
     * Replaces system placeholders such as {PORT} or {HOST} in env map or command strings.
     */
    fun resolvePlaceholders(input: String, port: Int, host: String = "127.0.0.1"): String {
        return input
            .replace("{PORT}", port.toString())
            .replace("\$PORT", port.toString())
            .replace("{HOST}", host)
            .replace("\$HOST", host)
    }
}
